# Run 'isi storagepool list' and send email if nodepool capacity exceeds threshold
# This is meant to be run from a cluster node directly and not remotely
#
# Tested on OneFS 8.0.0.4 with default Python 2.6.1 libraries
#
# joshua.lay@dell.com
# Last update 03-Jul-2018


from optparse import OptionParser
import subprocess
import socket
import time
import os
import sys
from isi.app.lib.emailer import Emailer


usage = "Usage: %prog"
parser = OptionParser(usage=usage, version='%prog 0.2', description="Send email if nodepool exceeds specified threshold")
parser.add_option('-f', '--from', '--sender', dest='FROM', help="email sender (From:)")
parser.add_option('-t', '--to', '--recipients', dest='TO', help="email recipient (To:)", action='append', default=[])
parser.add_option('-s', '--subject', dest='SUBJECT', help="email subject (Subject:)", default="Isilon Node Pool Utilization Exceeds Threshold")
parser.add_option('-T', '--threshold', dest='THRESHOLD', help="Threshold for any nodepool in percent.  e.g. 74 = 74%.  Default = 80%", type='int', default=80)
#parser.add_option('--test') #TODO
opts, args = parser.parse_args()


if (opts.FROM == None):
    fqdn = socket.getfqdn()
    opts.FROM = "donotreply@%s" % fqdn

if (opts.TO == None):    
	parser.error("Unable to send mail without at least one recipient")
	sys.exit(1)


CLUSTER_NAME = socket.gethostname().split('-')[0]
HOSTNAME = socket.gethostname()
DATE = time.ctime()


def isi_storagepool_list():
    '''Run 'isi storagepool list' command and return tuple of node pools that exceed threshold and command output string'''
    cmd = ['isi', 'storagepool', 'list']
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE)
    output = p.communicate()[0]
    
    lines = output.splitlines()
    np_lines = lines[2:-2]
    pools = []
    for p in np_lines:
        pools.append(p.split())
        
    return (pools, output)


POOLS, CMD_OUTPUT = isi_storagepool_list()

body = '''\
<html>
    <body>
        <p>Do not reply to this message</p>
        <p>Cluster <samp>'{cluster}'</samp> has one or more node pools that have exceeded a utilization threshold of {pct}%.</p>
        <p>Date/Time: <samp>{date}</samp></p>
        <p>This message was generated by script: <code>{script}</code></p>
        <p>\n</p>
        <pre>{hostname}# isi storagepool list \n{output}</pre>
    </body>
</html>
'''.format(cluster=CLUSTER_NAME, pct=opts.THRESHOLD, date=DATE, script=os.path.abspath(__file__), output=CMD_OUTPUT, hostname=HOSTNAME)


def main():
    #print("executing main")
    send_mail = False

    # Check if any node pools exceed threshold
    for pool in POOLS:
        hdd_pct = float(pool[5].strip('%'))
        if (hdd_pct >= opts.THRESHOLD):
            send_mail = True

    # Send email
    if (send_mail == True):
        try:
            Emailer.send_email(opts.TO, body, opts.FROM, opts.SUBJECT)
        except:
            print("Error sending email.")
            sys.exit(1)

    sys.exit(0)



if __name__ == "__main__":
    main()
